### ISSUE TITLE
errorENV_CONFIG

### ISSUE THREAD

**Issue by zcchenvy** [cts198859/deeprl_signal_control#12]
File "C:\Users\chenvy\Anaconda3\envs\chenvy\lib\configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'ENV_CONFIG'

**Comment by zcchenvy** [comment]
I tested files in envs, and find this error. and i have no idea how to figure it out. Has any one encountered this problem？

**Comment by cts198859** [comment]
This implies `ENV_CONFIG` is not included in the config file. Are you loading the config file correctly under `configs/`?
