### ISSUE TITLE
test

### ISSUE THREAD

**Issue by zzcNEU** [cts198859/deeprl_signal_control#13]
我没太看懂你们的配置，

default_base_dir = '/Users/tchu/Documents/rl_test/signal_control_results/eval_dec16/real_net’
default_config_dir = './config/config_test_large.ini'
修改成
default_base_dir = '/Users/thnx1/Desktop/硕士论文/code/deeprl_signal_control-master/control_results/real_net'
default_config_dir = '/Users/thnx1/Desktop/硕士论文/code/deeprl_signal_control-master/config/config_test_large.ini'
可以吗？

**Comment by cts198859** [comment]
base_dir is any new directory and config_dir is the path to the config file. Your setting is okay, but please make sure to input the correct config file for the experiment. For example if you want to train MA2C for the real network, you should use ./config/config_ma2c_real.ini. config_test_large.ini is for testing so no RL model will be trained.

**Comment by zzcNEU** [comment]
thank you
