### ISSUE TITLE
Can't run build_file.py

### ISSUE THREAD

**Issue by Vonisoa** [cts198859/deeprl_signal_control#15]
Hi, I try to run the deeprl_signal_control. But when I am in the step to run the build_file.py, I have this following error:

> Loading configuration... done.
> Error: Invalid edge id 'e:np1,nt1'.
> Error: The connection-source edge 'e:np1,nt1' is not known.
> Error: The connection-source edge 'e:np1,nt1' is not known.
> Error: The connection-source edge 'e:np1,nt1' is not known.
> Error: The connection-source edge 'e:np2,nt1' is not known.
> Error: The connection-source edge 'e:np2,nt1' is not known.
> Error: The connection-source edge 'e:np2,nt1' is not known.
> Error: The connection-source edge 'e:np3,nt1' is not known.
> Error: The connection-source edge 'e:np3,nt1' is not known.
> Error: The connection-source edge 'e:np3,nt1' is not known.
> Error: The connection-source edge 'e:np8,nt4' is not known.
> Error: The connection-source edge 'e:np8,nt4' is not known.
> Error: The connection-source edge 'e:np9,nt4' is not known.
> Error: The connection-source edge 'e:np9,nt4' is not known.
> Error: The connection-source edge 'e:nt1,npc' is not known.
> Error: The connection-source edge 'e:nt1,npc' is not known.
> Error: The connection-source edge 'e:nt1,nt2' is not known.
> Error: The connection-source edge 'e:nt1,nt2' is not known.
> Error: The connection-source edge 'e:nt3,nt2' is not known.
> Error: The connection-source edge 'e:nt3,nt2' is not known.
> Error: The connection-source edge 'e:nt1,nt6' is not known.
> Error: The connection-source edge 'e:nt1,nt6' is not known.
> Error: The connection-source edge 'e:nt5,nt6' is not known.
> Error: The connection-source edge 'e:nt5,nt6' is not known.
> Error: The connection-source edge 'e:npc,nt3' is not known.
> Error: The connection-source edge 'e:npc,nt3' is not known.
> Error: The connection-source edge 'e:nt4,nt3' is not known.
> Error: The connection-source edge 'e:nt4,nt3' is not known.
> Error: The connection-source edge 'e:npc,nt5' is not known.
> Error: The connection-source edge 'e:npc,nt5' is not known.
> Error: The connection-source edge 'e:nt4,nt5' is not known.
> Error: The connection-source edge 'e:nt4,nt5' is not known.
> Error: No edges loaded.
> Quitting (on error).
> Error: The network file 'exp.net.xml' is not accessible.
> Quitting (on error).
Could anyone help please?

**Comment by cts198859** [comment]
I was able to run it. Did you pull the latest master and ran it under `./small_grid/data`?

**Comment by Vonisoa** [comment]
I got it working inside small_grid an large_grid know.
But I get another error when running the main.py:

> Traceback (most recent call last):
>   File "main.py", line 224, in <module>
>     train(args)
>   File "main.py", line 95, in train
>     total_step = int(config.getfloat('TRAIN_CONFIG', 'total_step'))
>   File "C:\Users\vonisoa\AppData\Local\Programs\Python\Python36\lib\configparser.py", line 824, in getfloat
>     fallback=fallback, **kwargs)
>   File "C:\Users\vonisoa\AppData\Local\Programs\Python\Python36\lib\configparser.py", line 809, in _get_conv
>     **kwargs)
>   File "C:\Users\vonisoa\AppData\Local\Programs\Python\Python36\lib\configparser.py", line 803, in _get
>     return conv(self.get(section, option, **kwargs))
>   File "C:\Users\vonisoa\AppData\Local\Programs\Python\Python36\lib\configparser.py", line 781, in get
>     d = self._unify_values(section, vars)
>   File "C:\Users\vonisoa\AppData\Local\Programs\Python\Python36\lib\configparser.py", line 1141, in _unify_values
>     raise NoSectionError(section)
> configparser.NoSectionError: No section: 'TRAIN_CONFIG'
