### ISSUE TITLE
Display the scenario

### ISSUE THREAD

**Issue by Vonisoa** [cts198859/deeprl_signal_control#17]
Hi, It's still me. I want to know if there is an option to display the scenario when we have trained the agents to compare visually the difference between different scenario implemented.
Thanks.

**Comment by cts198859** [comment]
Yes, `env.reset(gui=True)` will launch the SUMO gui for visualization. I will update the repo shortly regarding this feature.

**Comment by Vonisoa** [comment]
Ok, thank you in advance.

**Comment by Vonisoa** [comment]
In wich file do we add the `env.reset(gui=True)` please?

**Comment by cts198859** [comment]
You do not need to do this anymore. Just follow step 4 in Usages: adding `--demo` when you run evaluation. I have changed the code so please do not change the structure of `ma2c` folder after training.
