### ISSUE TITLE
Agent not recognized when running evaluate

### ISSUE THREAD

**Issue by Vonisoa** [cts198859/deeprl_signal_control#18]
Hi, I could run the trainnning of ma2c on large grid (for 5 days of trainning). But now, I want to evaluate it.
When I run this command:
`python main.py --base-dir test_dir evaluate --agents ma2c --evaluate-seeds 3`
I got the following error:

> [ERROR] Evaluation: ma2c does not exist!

Of course, the folder `ma2c `really not exists in `test_dir`.
What have I done wrong? could you help please?

**Comment by cts198859** [comment]
The evaluation path should match your training path. Say if `base-dir=/xx/test_dir` in your training (and the trained model is stored under `/xx/test_dir/model`), please rename `test_dir` as `ma2c` and pass `base-dir=/xx`, `agents=ma2c` in your evaluation. Alternatively, you can modify `main.evaluate_fn` to import an arbitrary path.

**Comment by Vonisoa** [comment]
Thank you. But I will add some tip to your answer. The checkpoints files should be directly put inside `ma2c ` but not in `ma2c/model` and we need to add the configuration file `.ini` inside `ma2c `to.

**Comment by cts198859** [comment]
Sorry for the confusion. Now you can pass `ma2c` as it is, i.e., `.ini` under `ma2c/data` and model files under `ma2c/model`.
