### ISSUE TITLE
build_file.py fails in real_net

### ISSUE THREAD

**Issue by Vonisoa** [cts198859/deeprl_signal_control#19]
Hi, I now want to try the real net. But when I run the buil_file.py I got the following error:
`ModuleNotFoundError: No module named 'envs'`
But when I append the path of the `envs`, I got another error so could you help please?
Another question, isn't there a config in `small grid for ma2c` ?

**Comment by cts198859** [comment]
Hi, you do not need to call build_file.py for real_net, as stated in the README: "Before training, please call build_file.py under [environment_dir]/data/ to generate SUMO network files for small_grid and large_grid environments." The network files of real_net have been manually generated.
