### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'sumoD': 'sumoD'

### ISSUE THREAD

**Issue by Brucewangxq** [cts198859/deeprl_signal_control#20]
when I run "main.py train", the Error happen!
Traceback (most recent call last):
  File "main.py", line 216, in <module>
    train(args)
  File "main.py", line 88, in train
    env = init_env(config['ENV_CONFIG'])
  File "main.py", line 64, in init_env
    return RealNetEnv(config, port=port)
  File "/home/bruce/deeprl_signal_control-master/envs/real_net_env.py", line 117, in __init__
    super().__init__(config, output_path, is_record, record_stat, port=port)
  File "/home/bruce/deeprl_signal_control-master/envs/env.py", line 105, in __init__
    self._init_sim(self.seed)
  File "/home/bruce/deeprl_signal_control-master/envs/env.py", line 288, in _init_sim
    subprocess.Popen(command)
  File "/home/bruce/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/bruce/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sumoD': 'sumoD'

I'm very sad, who can do me a favor?

**Comment by Brucewangxq** [comment]
may be I need to install or compile something related to SUMO ? If it is, how should I do it?

**Comment by Brucewangxq** [comment]
I also have done the steps of 'setup_ubuntu.sh' , but its useless, the error still existing.

**Comment by cts198859** [comment]
Are you able to run sumo independently? Say under `/real_net/data` run `sumo-gui -c most.sumocfg`.

**Comment by cts198859** [comment]
You are using Windows, right? Then you have to build SUMO in a different way to generate sumoD https://sumo.dlr.de/docs/Downloads.html. Note this repo is mainly for mac and linux/ubuntu machines and I have not tested it on Windows.

**Comment by Brucewangxq** [comment]
Indeed, I am using Ubuntu. Under /real_net/data run sumo-gui -c most.sumocfg. when I independently run it, successful,

**Comment by Brucewangxq** [comment]
First, the same problem still existing; Then, I 'print(command)' before 'subprocess.Popen(command)', Output: ['sumoD', '-c', './real_net/data/most_0.sumocfg', '--seed', '42', '--remote-port', '8000', '--no-step-log', 'True', '--time-to-teleport', '300', '--no-warnings', 'True', '--duration-log.disable', 'True']
But, FileNotFoundError: [Errno 2] No such file or directory: 'sumoD': 'sumoD'

**Comment by Brucewangxq** [comment]
anyone could give me any advice?

**Comment by cts198859** [comment]
Which SUMO version are you using? Could you replace line 277 of `envs/env.py` to `command = [app, '-c', sumocfg_file]` and try it again?

**Comment by Brucewangxq** [comment]
Great! just change to app. Thanks very much!
