### ISSUE TITLE
About the traffic flow file, rou.xml 

### ISSUE THREAD

**Issue by Brucewangxq** [cts198859/deeprl_signal_control#21]
I am training the ma2c model in the real net scenario, but the training reward curve just start at -14 or so, then with the increase of training time the average episode reward converges to -9 or so, enventually. But the the reward curve of the original paper changes from -125 converge to -30 or so. I want to know the reason about that, may be I have a wrong flow-config? Could you give me any advice?

**Comment by cts198859** [comment]
Could you provide more details: 1) which SUMO version are you using? 2) which command / config file did you use to run the training?

**Comment by Brucewangxq** [comment]
The version of SUMO is "sumo 已经是最新版 (1.2.0+dfsg1-14~xenial)“。
I am using the 'config_ma2c_real.ini'

**Comment by Brucewangxq** [comment]
By the way, there have no 'most.rou.xml', so when I run the project,  new files named 'most_0.rou.xml' and 'most_0.sumocfg' will be created basing these existed files 'most.net.xml' and 'most.add.xml'. The existing file 'most.sumocfg' may not be used.

**Comment by Brucewangxq** [comment]
I am sorry to bother you, but l urgently have some work involving a real net. If I want to modify the the nature of intersections, such as, phase and  the number of lanes. Could you give me some advice? Thanks a lot. Maybe e-mail is OK for me. 1320293590@qq.com

**Comment by Brucewangxq** [comment]
Now, I have reproducted the training curve of ma2c in "real net" . Thanks, sincerely. But If I want to modify the the nature of intersections, such as, phase and the number of lanes. Could you give me some advice?

**Comment by cts198859** [comment]
SUMO 1.2.0 does not seem like a stable version. Could you try 1.1.0 or the latest 1.3.0 instead? The config file is correct. To modify the network topology in a real net, you need to 1) modify the network file (e.g. `real_net/data/in/most.net.xml`) for SUMO, and 2) import the correct intersection config `NODES={intersection_id: (phase, neighbor_intersection_ids)` in `envs/real_net_env.py`. Step 1) may require a lot of engineering efforts, while step 2) is relatively straight-forward, assuming you have some coding background.
