### ISSUE TITLE
problem of memory cannot allocate

### ISSUE THREAD

**Issue by ynuwm** [cts198859/deeprl_signal_control#25]
I just train the first model IA2C, it occurs a error, can you help me?
```p
Traceback (most recent call last):
  File "main.py", line 230, in <module>
    train(args)
  File "main.py", line 129, in train
    trainer.run()
  File "/project/wangmin/Multi-Agent-master/utils.py", line 278, in run
    ob = self.env.reset()
  File "/project/wangmin/Multi-Agent-master/envs/env.py", line 562, in reset
    self._init_sim(seed, gui=gui)
  File "/project/wangmin/Multi-Agent-master/envs/env.py", line 301, in _init_sim
    subprocess.Popen(command)
  File "/software/google/tensorflow/python3.6-cpu/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/software/google/tensorflow/python3.6-cpu/lib/python3.6/subprocess.py", line 1295, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
```

**Comment by cts198859** [comment]
Which tensorflow version are you using? `subprocess` should NOT be imported from `tensorflow`. https://docs.python.org/3/library/subprocess.html

**Comment by ynuwm** [comment]
it need to change this line
```p
subprocess.Popen(command, close_fds=True)
```
so, child process will be killed automatically.

**Comment by cts198859** [comment]
Thanks for the info, and I am glad to see this works for you. This is interesting: it seems `close_fds=True` is the default based on the doc. Can you give me more context so that I can reproduce the above error?

**Comment by ynuwm** [comment]
in utils.py your code is: 
```p
# train
self.env.train_mode = True
ob = self.env.reset()
# note this done is pre-decision to reset LSTM states!
done = True
self.model.reset()
self.cur_step = 0
rewards = []
while True:
    ob, done, R, cur_rewards = self.explore(ob, done)
    rewards += cur_rewards
    global_step = self.global_counter.cur_step
    if self.agent.endswith('a2c'):
        self.model.backward(R, self.summary_writer, global_step)
    else:
        self.model.backward(self.summary_writer, global_step)
    # termination
    if done:
        self.env.terminate()
        break
```
if I add this ```close_fds=True``` in ```subprocess.Popen(command, close_fds=True)```, 
```ob = self.env.reset()``` will not report error.
Otherwise, error will occur at line  ```ob = self.env.reset()``` .

**Comment by cts198859** [comment]
Thanks. Could you provide more information: what OS are you using? How did you install tensorflow and python? Did you use `setup_mac.sh` or `setup_ubuntu.sh` to install the requirements?

**Comment by ynuwm** [comment]
I use the server of the school's supercomputing center. I neither use ```setup_mac.sh``` nor ```setup_ubuntu.sh```. I also didn't use GPU. Now the school's server is malfunctioning. After the recovery, I upload the system information. I guess our school's server system is Red hat.

**Comment by cts198859** [comment]
I see. The code has not been tested on that OS so it may have unexpected behavior. Based on the error message, it may also because the server system cannot allocate memory to your job. Then I think the best way is to contact the IT support at your school about this issue.

**Comment by ynuwm** [comment]
Now I can run the program normally, I have a question about your setting ```total_step = 1e6```, can you set the total step size smaller and improve learning rate. Otherwise it takes a long time to train the model well. The program ran for 15 hours and only ran 160,000 steps.

**Comment by cts198859** [comment]
Feel free to tune the hyper parameters based on your need. You can modify the code/config on your local copy.

**Comment by ynuwm** [comment]
Thank you. I have a question about the output lines of this,
``` 
nt1:
        neigbor: ['nt6', 'nt2']
        ilds_in: ['nt6_nt1_0', 'nt2_nt1_0', 'nt2_nt1_1', 'np1_nt1_0', 'np20_nt1_0', 'np20_nt1_1']
```
what is np20 means? can you help me explain it?

**Comment by ynuwm** [comment]
Do you have a WeChat, I have some other confusions. Thank you.
