### ISSUE TITLE
Could not connect to TraCI server at localhost:8000 [Errno 111] Connection refused.

### ISSUE THREAD

**Issue by parksanha** [cts198859/deeprl_signal_control#27]
Hi~.

There was a problem while training.

When I write the code, I get the following error. How do I fix it?

code : "python3 main.py --base-dir large_grid/ma2c train --config-dir config/config_ma2c_large.ini --test-mode no_test"
error : "Could not connect to TraCI server at localhost:8000 [Errno 111] Connection refused."

Thank you.

**Comment by parksanha** [comment]
I solved the problem.

**Comment by kxusx** [comment]
could you share how you solved this problem?
