### ISSUE TITLE
Adding phases.

### ISSUE THREAD

**Issue by parksanha** [cts198859/deeprl_signal_control#28]
When training large_grid

I want to change the phase and increase the number.

Which file should be modified at this time?

※ I modified the code as below.
1) large_grid.py
- line 20 : PHASE_NUM = 6
- line 40~41 : phases = ['GGrrrrGGrrrr', 'rrGrrrrrGrrr', 'rrrGGrrrrGGr', 'rrrrrGrrrrrG', 'rrrGGGrrrrrr', 'rrrrrrrrrGGG']

Is there any code I need to modify?

Thanks~

**Comment by cts198859** [comment]
Seems these are all you need to change. LMK if you have issues running it.

**Comment by parksanha** [comment]
It goes without a problem.

However, I think I only need to modify the [flow] in [def greedy].

Thanks.

**Comment by parksanha** [comment]
Let me ask you one more about phase.

The current logic is to choose the next phase of the given phases.

And, how do I proceed in the following way?
[Keep or change the current phase in a cycle-based phase sequence]
ex : phase1 → phase2 → phase3 → phase4 →phase1 → phase2 → phase3 → phase4 ...

Is this possible?

Can you help me?

**Comment by cts198859** [comment]
To do this, you need to re-formulate the MDP so that each action is a pre-defined cycle. Also the action space should contain all possible cycles instead of phases. I may not give further advises as this is not an issue related to this repo.
