### ISSUE TITLE
About distance_map

### ISSUE THREAD

**Issue by parksanha** [cts198859/deeprl_signal_control#30]
Hello.

I have a question about using [distance_map] in [ma2c].

If you look at line 610 of [env.py], you don't seem to be using [distance_map].

Is there any reason not to use [distance_map]?

It seems that [distance_map] is used in [Equation (9)] in the paper(preprint version).
(https://arxiv.org/pdf/1903.04527.pdf)

And how can I use [distance_map]?

Thank you.

**Comment by cts198859** [comment]
Good point. The commented out logic is not scalable for implementing distance map and it does not provide additional gain compared to neighborhood discount, so it is disabled. However, in another repo we implemented a scalable and generalized version of distance map, for any network https://github.com/cts198859/deeprl_network.
