### ISSUE TITLE
Can I use multi-threading during training?

### ISSUE THREAD

**Issue by parksanha** [cts198859/deeprl_signal_control#32]
Hello.

Can I use multi-threading during training?

How can I enable multi-threading in main.py?

**Comment by cts198859** [comment]
Yes you can explore this option. More details in another issue https://github.com/cts198859/deeprl_signal_control/issues/24#issue-570389545

**Comment by parksanha** [comment]
Thank you for the reply.

However, it is difficult for me to solve it myself with only #24, so I ask for help.

I enabled lines 105, 124, 128-145 in main.py, but it doesn't appear to be using multi-core.

Is there anything else I need to modify?

**Comment by cts198859** [comment]
May need to call Trainer.run_thread(). BTW, I did not complete the implementation of multi-threading due to SUMO issues (it cannot maintain multiple independent simulators). So it may take some time to explore this option.

**Comment by parksanha** [comment]
Thank you. I will try.
