### ISSUE TITLE
Comparison between models and SUMO default traffic lights program

### ISSUE THREAD

**Issue by alexandrevenot** [cts198859/deeprl_signal_control#34]
Hello,

Is there a simple way to compare the different models of the repo with the SUMO automatically generated TLS program?
If not, have you done it and how does it look?

**Comment by cts198859** [comment]
Yes, you can directly run SUMO using the config file instead of calling it from our simulator. Then the default TLS will be applied. I manually checked a few runs in GUI and it did not perform well (rules are pre-fixed, not even greedy).

**Comment by alexandrevenot** [comment]
Okay, and did you try it on the Monaco map?

Because I tried to compare the ma2c model and the default TLS on Monaco, here's how I proceeded:

With the same seed, by prohibiting teleportations due to jam, and for a 3600-iteration simulation,

- On one side, I ran SUMO with the config file this way:

`sumo -c most_0.sumocfg --seed 5 --tripinfo-output.write-unfinished --tripinfo-output defaultTLS_trips.xml --time-to-teleport -1`

- On the other side, after modifying the line 282 of `envs/env.py` to
```python
            command += ['--time-to-teleport', '-1'] # long teleport for safety
```
and adding this line right after the line 288:
```python
            command += ['--tripinfo-output.write-unfinished']
```
I ran your simulator this way:
`python main.py --base-dir [base_dir] evaluate --agents ma2c --evaluation-seeds 5 --demo`
___
The fact is, based on the trips.xml output comparison, it looks like the ma2c model (that I trained with the default .ini config file on 1M steps) performance is below the default TLS performance.

Am I missing something, or doing something wrong?

**Comment by cts198859** [comment]
Interesting. Did you also train the model with `--time-to-teleport -1`? It might learn a different simulator behavior.

**Comment by alexandrevenot** [comment]
My bad, I assumed the model was being trained with teleportations disabled.

I trained it again, it took 60% more time ; and now it looks like when being tested with teleportations disabled, the performance of the MA2C is higher than the default TLS performance. Thanks a lot!
