### ISSUE TITLE
About modifing ma2c model.

### ISSUE THREAD

**Issue by parksanha** [cts198859/deeprl_signal_control#35]
Hello?

I want to compare the difference between whether an intersection checks the state(also reward) of the neighborhood or not.

If I want to make a model that does not check the state of neighbors, can I delete all the neighbors list from the [large_grid_env.py] file after setting the ma2c model?

ex) neighbor_map['nt1'] = ['nt6','nt2'] →neighbor_map['nt1'] = []

**Comment by cts198859** [comment]
You get the idea. Or you can just return an empty {} in `def _init_large_neighbor_map(self)`. Note this ignores both states and rewards from neighbors.
