### ISSUE TITLE
Are there all evaluation data in one .xml file?

### ISSUE THREAD

**Issue by cp-lab-uts** [cts198859/deeprl_signal_control#36]
I test ma2c model, and I only get one evaluation data  eva_data\large_grid_ma2c_trip.xml file. I cannot get data like time-series data from this file. I want to know how to generate the data like your eva_data file (control.csv, traffic.csv, trip.csv).

Thanks!!

**Comment by cts198859** [comment]
For evaluation run, they will be automatically output to `[base_dir]/eva_data`:
https://github.com/cts198859/deeprl_signal_control/blob/c3cadbd088a3f6946ecba667fd07cbd689947d32/main.py#L203

However, you need to wait until the run finishes to see the data:
https://github.com/cts198859/deeprl_signal_control/blob/c3cadbd088a3f6946ecba667fd07cbd689947d32/utils.py#L388

Of course, you can modify the simulator to customize the output data:
https://github.com/cts198859/deeprl_signal_control/blob/c3cadbd088a3f6946ecba667fd07cbd689947d32/envs/env.py#L534

Hope this answers your question.

**Comment by cp-lab-uts** [comment]
Thank you for your reply! I guess there was something wrong when I test the model. I will try it again!
