### ISSUE TITLE
Evaluate

### ISSUE THREAD

**Issue by HappyDay-design** [cts198859/deeprl_signal_control#46]
Hello

Thank you very much
I created a new folder called Results. And training

After 2 training -days, I got the results of the model. But I had errors when evaluating

`python3 main.py --base-dir [base_dir] evaluate --agents [agents] --evaluation-seeds [seeds]`

I have trouble with `--agents [agents]` . I used ia2c in `config_ia2c_large.ini `so I wrote 

python3 main.py --base-dir Results evaluate --agents ia2c --evaluation-seeds [seeds]
Errors

**Comment by LayCYL** [comment]
> Hello
> 
> Thank you very much I created a new folder called Results. And training
> 
> After 2 training -days, I got the results of the model. But I had errors when evaluating
> 
> `python3 main.py --base-dir [base_dir] evaluate --agents [agents] --evaluation-seeds [seeds]`
> 
> I have trouble with `--agents [agents]` . I used ia2c in `config_ia2c_large.ini `so I wrote
> 
> python3 main.py --base-dir Results evaluate --agents ia2c --evaluation-seeds [seeds] Errors

Have you successfully reproduced the code in this repository？
